/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var wison = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,16],$V1=[1,22],$V2=[2,14,23],$V3=[2,41,43],$V4=[1,37],$V5=[1,48],$V6=[1,49],$V7=[1,45],$V8=[1,46],$V9=[1,47],$Va=[2,18,42],$Vb=[27,32],$Vc=[27,31],$Vd=[27,32,34,35,36],$Ve=[27,47],$Vf=[1,64],$Vg=[1,63],$Vh=[2,42],$Vi=[24,27,42,47];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"analizador":3,"wison":4,"EOF":5,"WISON":6,"APERTURA":7,"lexico":8,"sintactico":9,"CIERRE":10,"LEX":11,"IN_LEX":12,"reglas_lexicas":13,"FIN_LEX":14,"SYNTAX":15,"IN_SYNTAX":16,"syntax":17,"FIN_SYNTAX":18,"no_terminales":19,"inicio":20,"producciones":21,"regla_lexica":22,"TERMINAL":23,"TERMINAL_NOMBRE":24,"FLECHA":25,"expr":26,"P_COMA":27,"unario":28,"combinado":29,"concatenacion":30,"PAREN_IZQ":31,"PAREN_DER":32,"simple":33,"KLEENE":34,"POSITIVO":35,"OPCIONAL":36,"CADENA":37,"LETRAS":38,"DIGITOS":39,"no_terminal":40,"NO_TERMINAL":41,"NO_TERMINAL_NOMBRE":42,"INICIO":43,"produccion":44,"ASIGNACION":45,"reglas":46,"OR":47,"listaSimbolos":48,"simbolo":49,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",6:"WISON",7:"APERTURA",10:"CIERRE",11:"LEX",12:"IN_LEX",14:"FIN_LEX",15:"SYNTAX",16:"IN_SYNTAX",18:"FIN_SYNTAX",23:"TERMINAL",24:"TERMINAL_NOMBRE",25:"FLECHA",27:"P_COMA",31:"PAREN_IZQ",32:"PAREN_DER",34:"KLEENE",35:"POSITIVO",36:"OPCIONAL",37:"CADENA",38:"LETRAS",39:"DIGITOS",41:"NO_TERMINAL",42:"NO_TERMINAL_NOMBRE",43:"INICIO",45:"ASIGNACION",47:"OR"},
productions_: [0,[3,2],[4,6],[8,4],[9,4],[17,3],[13,2],[13,2],[13,1],[13,1],[22,5],[26,1],[26,1],[29,2],[29,1],[30,3],[28,2],[28,2],[28,2],[28,1],[33,1],[33,1],[33,1],[33,1],[19,2],[19,2],[19,1],[19,1],[40,3],[20,3],[21,2],[21,2],[21,1],[21,1],[44,4],[46,3],[46,2],[46,1],[46,0],[48,2],[48,1],[49,1],[49,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: case 7:
 this.$ = $$[$0-1]; 
break;
case 2:
 this.$ = new Creador($$[$0-3], $$[$0-2]); 
break;
case 3: case 4: case 15: case 25: case 31:
 this.$ = $$[$0-1] 
break;
case 5:
 this.$ = new Syntax($$[$0-2], $$[$0-1], $$[$0]) 
break;
case 6: case 24: case 30: case 39:
 this.$ = $$[$0-1]; $$[$0-1].push($$[$0]) 
break;
case 8:
 this.$ = [$$[$0]]; 
break;
case 9:
 this.$ = []; 
break;
case 10:
 this.$ = new ReglaLexica($$[$0-3], $$[$0-1], _$[$0-3].first_line, _$[$0-3].first_column) 
break;
case 11: case 12: case 19:
 this.$ = $$[$0] 
break;
case 13:
 $$[$0-1].agregarExpresion($$[$0]); this.$ = $$[$0-1] 
break;
case 14:
 this.$ = new Concatenacion($$[$0]) 
break;
case 16:
 this.$ = new Kleene($$[$0-1]) 
break;
case 17:
 this.$ = new Positiva($$[$0-1]) 
break;
case 18:
 this.$ = new Opcional($$[$0-1]) 
break;
case 20:
 this.$ = new Cadena($$[$0]) 
break;
case 21: case 22:
 this.$ = new Secuencia($$[$0]) 
break;
case 23:
 this.$ = new IdentiExpresion($$[$01], _$[$01].first_line, _$[$01].first_column) 
break;
case 26: case 32: case 37: case 40:
 this.$ = [$$[$0]] 
break;
case 27: case 33:
 this.$ = [] 
break;
case 28:
 this.$ = new NoTerminal($$[$0-1], _$[$0-1].first_line, _$[$0-1].first_column) 
break;
case 29:
 this.$ = new Inicial($$[$0-1], _$[$0-1].first_line, _$[$0-1].first_column) 
break;
case 34:
 this.$ = new Produccion($$[$0-3], $$[$0-1], _$[$0-3].first_line, _$[$0-3].first_column) 
break;
case 35:
 this.$ = $$[$0-2]; $$[$0-2].push($$[$0]) 
break;
case 36:
 this.$ = $$[$0-1]; $$[$0-1].push([new Simbolo("", this._$.first_line, this._$.first_column, true)]) 
break;
case 38:
 this.$ = [[new Simbolo("", this._$.first_line, this._$.first_column, true)]] 
break;
case 41:
 this.$ = new Simbolo($$[$0], _$[$0].first_line, _$[$0].first_column, false) 
break;
case 42:
 this.$ = new Simbolo($$[$0], _$[$0].first_line, _$[$0].first_column, true) 
break;
}
},
table: [{3:1,4:2,6:[1,3]},{1:[3]},{5:[1,4]},{7:[1,5]},{1:[2,1]},{8:6,11:[1,7]},{9:8,15:[1,9]},{12:[1,10]},{10:[1,11]},{16:[1,12]},{2:[1,15],13:13,22:14,23:$V0},{6:[1,17]},{2:[1,21],17:18,19:19,40:20,41:$V1},{2:[1,25],14:[1,23],22:24,23:$V0},o($V2,[2,8]),o($V2,[2,9]),{24:[1,26]},{5:[2,2]},{18:[1,27]},{2:[1,30],20:28,40:29,41:$V1,43:[1,31]},o($V3,[2,26]),o($V3,[2,27]),{42:[1,32]},{15:[2,3]},o($V2,[2,6]),o($V2,[2,7]),{25:[1,33]},{10:[2,4]},{2:[1,36],21:34,42:$V4,44:35},o($V3,[2,24]),o($V3,[2,25]),{42:[1,38]},{27:[1,39]},{24:$V5,26:40,28:41,29:42,30:44,31:$V6,33:43,37:$V7,38:$V8,39:$V9},{2:[1,51],18:[2,5],42:$V4,44:50},o($Va,[2,32]),o($Va,[2,33]),{45:[1,52]},{27:[1,53]},o($V3,[2,28]),{27:[1,54]},{27:[2,11]},{27:[2,12],30:55,31:$V6},o($Vb,[2,19],{34:[1,56],35:[1,57],36:[1,58]}),o($Vc,[2,14]),o($Vd,[2,20]),o($Vd,[2,21]),o($Vd,[2,22]),o($Vd,[2,23]),{24:$V5,28:59,33:43,37:$V7,38:$V8,39:$V9},o($Va,[2,30]),o($Va,[2,31]),o($Ve,[2,38],{46:60,48:61,49:62,24:$Vf,42:$Vg}),o($Vh,[2,29]),o($V2,[2,10]),o($Vc,[2,13]),o($Vb,[2,16]),o($Vb,[2,17]),o($Vb,[2,18]),{32:[1,65]},{27:[1,66],47:[1,67]},o($Ve,[2,37],{49:68,24:$Vf,42:$Vg}),o($Vi,[2,40]),o($Vi,[2,41]),o($Vi,$Vh),o($Vc,[2,15]),o($Va,[2,34]),o($Ve,[2,36],{49:62,48:69,24:$Vf,42:$Vg}),o($Vi,[2,39]),o($Ve,[2,35],{49:68,24:$Vf,42:$Vg})],
defaultActions: {4:[2,1],17:[2,2],23:[2,3],27:[2,4],41:[2,11]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse (input) {
    var self = this,
        stack = [0],
        tstack = [], // token stack
        vstack = [null], // semantic value stack
        lstack = [], // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }

    function popStack (n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

_token_stack:
    var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        // retreive state number from top of stack
        state = stack[stack.length - 1];

        // use default actions if available
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            // read action for current state and first input
            action = table[state] && table[state][symbol];
        }

_handle_error:
        // handle parse error
        if (typeof action === 'undefined' || !action.length || !action[0]) {
            var error_rule_depth;
            var errStr = '';

            // Return the rule stack depth where the nearest error rule can be found.
            // Return FALSE when no error recovery rule was found.
            function locateNearestErrorRecoveryRule(state) {
                var stack_probe = stack.length - 1;
                var depth = 0;

                // try to recover from error
                for(;;) {
                    // check for error recovery rule in this state
                    if ((TERROR.toString()) in table[state]) {
                        return depth;
                    }
                    if (state === 0 || stack_probe < 2) {
                        return false; // No suitable error recovery rule available.
                    }
                    stack_probe -= 2; // popStack(1): [symbol, action]
                    state = stack[stack_probe];
                    ++depth;
                }
            }

            if (!recovering) {
                // first see if there's any chance at hitting an error recovery rule:
                error_rule_depth = locateNearestErrorRecoveryRule(state);

                // Report error
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push("'"+this.terminals_[p]+"'");
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line '+(yylineno+1)+":\n"+lexer.showPosition()+"\nExpecting "+expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol)+ "'";
                } else {
                    errStr = 'Parse error on line '+(yylineno+1)+": Unexpected " +
                                  (symbol == EOF ? "end of input" :
                                              ("'"+(this.terminals_[symbol] || symbol)+"'"));
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: (error_rule_depth !== false)
                });
            } else if (preErrorSymbol !== EOF) {
                error_rule_depth = locateNearestErrorRecoveryRule(state);
            }

            // just recovered from another error
            if (recovering == 3) {
                if (symbol === EOF || preErrorSymbol === EOF) {
                    throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
                }

                // discard current lookahead and grab another
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                symbol = lex();
            }

            // try to recover from error
            if (error_rule_depth === false) {
                throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
            }
            popStack(error_rule_depth);

            preErrorSymbol = (symbol == TERROR ? null : symbol); // save the lookahead token
            symbol = TERROR;         // insert generic error symbol as new lookahead
            state = stack[stack.length-1];
            action = table[state] && table[state][TERROR];
            recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
        }

        // this shouldn't happen, unless resolve defaults are off
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: '+state+', token: '+symbol);
        }

        switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution/no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                break;

            case 2:
                // reduce
                //this.reductionCount++;

                len = this.productions_[action[1]][1];

                // perform semantic action
                yyval.$ = vstack[vstack.length-len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack.length-(len||1)].first_line,
                    last_line: lstack[lstack.length-1].last_line,
                    first_column: lstack[lstack.length-(len||1)].first_column,
                    last_column: lstack[lstack.length-1].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack.length-(len||1)].range[0], lstack[lstack.length-1].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    return r;
                }

                // pop off stack
                if (len) {
                    stack = stack.slice(0,-1*len*2);
                    vstack = vstack.slice(0, -1*len);
                    lstack = lstack.slice(0, -1*len);
                }

                stack.push(this.productions_[action[1]][0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length-2]][stack[stack.length-1]];
                stack.push(newState);
                break;

            case 3:
                // accept
                return true;
        }

    }

    return true;
}};

    const { Cadena } = require('../backend/lexer/Cadena');
    const { Secuencia } = require('../backend/lexer/Secuencia')
    const { Kleene } = require('../backend/lexer/unarios/Kleene');
    const { Opcional } = require('../backend/lexer/unarios/Opcional');
    const { Positiva } = require('../backend/lexer/unarios/Positiva');
    const { IdentiExpresion } = require('../backend/lexer/IdentiExpresion');
    const { Concatenacion } = require('../backend/lexer/Concatenacion');
    const { ReglaLexica } = require('../backend/lexer/ReglaLexica');
    const { Creador } = require('../backend/CreadorGramatica/Creador');
    const { Simbolo } = require('../backend/syntax/Simbolo')
    const { NoTerminal } = require('../backend/syntax/NoTerminal')
    const { Inicial } = require('../backend/syntax/Inicial')
    const { Produccion } = require('../backend/syntax/Produccion')
    const { Syntax } = require('../backend/syntax/Syntax')

    function errorLexico(){
        if (!this.yy) this.yy = {};
        if (!this.yy.errores) this.yy.errores = [];
        this.yy.errores.push(
            {
                tipo: "Lexico",
                lexema: yytext,
                linea: yylloc.first_line,
                columna: yylloc.first_column,
                descripcion: `Caracter no reconocido: ${yytext}`
            }
        )
    }

    function traducirToken(token) {
        switch(token) {
            case "P_COMA": return ";";
            case "FLECHA": return "<-";
            case "ASIGNACION": return "<=";
            case "OR": return "|";
            case "PAREN_IZQ": return "(";
            case "PAREN_DER": return ")";
            case "KLEENE": return "*";
            case "POSITIVO": return "+";
            case "OPCIONAL": return "?";
            case "TERMINAL": return "Terminal";
            case "LEX": return "Lex";
            case "SYNTAX": return "Syntax";
            case "WISON": return "Wison";
            case "IN_LEX": return "{:";
            case "FIN_LEX": return ":}";
            case "IN_SYNTAX": return "{{:";
            case "FIN_SYNTAX": return ":}}";
            case "APERTURA": return "¿";
            case "CIERRE": return "?";
            case "NO_TERMINAL": return "No_Terminal";
            case "INICIO": return "Initial_Sim";
            case "TERMINAL_NOMBRE": return "$_NOMBRE";
            case "NO_TERMINAL_NOMBRE": return "%_NOMBRE";
            case "CADENA": return "palabra reservada";
            case "LETRAS": return "[a-zA-Z]";
            case "DIGITOS": return "[0-9]";
            default: return token;
        }
    }

    function construirDescripcionError(expected) {
        if (!expected || expected.length === 0) {
            return "Ya no se esperaba ningún token en este punto";
        }
        const tokens = expected.map(t => traducirToken(t));
        return `Se esperaba: ${tokens.join(", ")}`;
    }

    parser.parseError = function (str, hash) {
        if (!this.yy) this.yy = {};
        if (!this.yy.errores) this.yy.errores = [];
        this.yy.errores.push({
            tipo: "Sintactico",
            lexema: hash.text || "",
            linea: hash.loc?.first_line || 0,
            columna: hash.loc?.first_column || 0,
            descripcion: construirDescripcionError(hash.expected)
        });
    };
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"locations":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* Ignorar espacios en blanco */
break;
case 1:/* Ignorar comentarios de una línea */
break;
case 2:this.begin('COMENTARIO')  /* Iniciar comentario de varias líneas */
break;
case 3:this.popState()  /* Finalizar comentario de varias líneas */
break;
case 4:/* Ignorar el contenido del comentario */
break;
case 5:return 23
break;
case 6:return 24
break;
case 7:return 25
break;
case 8:errorLexico()
break;
}
},
rules: [/^(?:([ \t\r\n]+))/,/^(?:#.*)/,/^(?:\/\*\*)/,/^(?:\*\/)/,/^(?:(.|\n))/,/^(?:Terminal\b)/,/^(?:\$_([a-zA-Z][a-zA-Z0-9_]*))/,/^(?:<-)/,/^(?:\[\^ \\t\\r\\n+                        return CADENA\n<LEX>"\[a-zA-Z\]"                            return LETRAS\n<LEX>"\[0-9\]"                               return DIGITOS\n<LEX>\\\*                                    return KLEENE\n<LEX>\\\+                                    return POSITIVO\n<LEX>\\\?                                    return OPCIONAL\n<LEX>\\\(                                    return PAREN_IZQ\n<LEX>\\\)                                    return PAREN_DER\n<LEX,SYNTAX>";"                            return P_COMA\n"Wison"                                    return WISON\n"¿"                                        return APERTURA\n"\?"                                        return CIERRE\n"Lex"                                      return LEX\n"Syntax"                                   return SYNTAX\n"\{\{:"                                      this\.begin\(SYNTAX\); return IN_SYNTAX\n":\}\}"                                      this\.begin\(INITIAL\); return FIN_SYNTAX\n"\{:"                                       this\.begin\(LEX\); return IN_LEX\n":\}"                                       this\.begin\(INITIAL\); return FIN_LEX\n<SYNTAX>"No_Terminal"                      return NO_TERMINAL\n<SYNTAX>"Initial_Sim"                      return INICIO\n<SYNTAX>"<="                               return ASIGNACION\n<SYNTAX>"%_"\{IDENTIFICADOR\}                return NO_TERMINAL_NOMBRE\n<SYNTAX>"\|"                                return OR\n<<EOF>>                                    return EOF.)/],
conditions: {"SYNTAX":{"rules":[1,2,6],"inclusive":false},"LEX":{"rules":[1,2,5,6,7,8],"inclusive":false},"COMENTARIO":{"rules":[3,4],"inclusive":false},"INITIAL":{"rules":[0,1,2],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = wison;
exports.Parser = wison.Parser;
exports.parse = function () { return wison.parse.apply(wison, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}